- hosts: vyos-routers
  connection: local
  tasks:
  - name: configure the remote device
    vyos_config:
      lines:
        - set nat destination rule 1 inbound-interface eth0
        - set nat destination rule 1 destination port 80
        - set nat destination rule 1 protocol tcp
        - set nat destination rule 1 translation address {{dest_ip}}
