- hosts: vyos-routers
  connection: local
  tasks:
  - name: add a host to the list of allowed in the firewall group
    vyos_config:
      lines:
        - set firewall group network-group MAGMA_AGW network "{{ MAGMA_AGW_IP }}/32"

